name = "Francisco Moreno"
rol = "Mechatronics Engineer"
email = "fj.morenovazquez@ugto.mx"
phone = "+52 (456) 124-1577"
birthday = "August 28, 2000"
location = "Valle de Santiago, Guanajauto, Mexico"
avatar = "./config/assets/avatars/my-avatar.png"
username = "fcomovaz" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29917.864643267225!2d-101.21427653344152!3d20.39389244045532!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842c8d0935957e15%3A0x3a870577baeca000!2sValle%20de%20Santiago%2C%20Gto.!5e0!3m2!1ses-419!2smx!4v1688689557775!5m2!1ses-419!2smx"
presentation = """
As a Mechatronics Engineering student, I am passionate about expanding my knowledge through research and embracing challenges to grow personally and professionally. My participation in extracurricular activities such as summer research programs has equipped me with valuable problem‑solving, teamwork, and communication skills. 

I enjoy sharing my knowledge with others and believe in the importance of collaborative learning. I am eager to contribute my enthusiasm and expertise to a dynamic and innovative team.
"""
