[[doing]]
title = "Machine Learning"
icon = "./config/assets/icons/ml.svg"
text = "Machine learning and deep learning models for various tasks."

[[doing]]
title = "Computer Vision"
icon = "./config/assets/icons/vision.svg"
text = "Point cloud processing, image processing, and data analysis."

[[doing]]
title = "Embedded Systems"
icon = "./config/assets/icons/embedded.svg"
text = "Development of embedded systems for various tasks (FPGA, AVR)."
