[[project]]
title = "Cicruitikz Gallery"
category = "LaTeX"
image = "https://raw.githubusercontent.com/fcomovaz/circuitikz-gallery/main/img_circuits/circuitikz.png"
url = "https://github.com/fcomovaz/circuitikz-gallery"