############## Education config #################
#################################################
[[education]]
title = "University of Guanajuato (ENMS SALAMANCA)"
timeline = "2015 — 2018"
description = "High school studies in the are of mechatronics technician (KOSEN like system)."

[[education]]
title = "University of Guanajuato (DICIS UGTO)"
timeline = "2018 — Present"
description = "Bachelor's degree in Mechatronics Engineering."


############## Experience config ################
#################################################
# [[experience]]
# title = "Web designer"
# timeline = "2010 — 2013"
# description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Arduino Programming"
value = "80%"

[[skill]]
title = "FPGA Programming"
value = "40%"

[[skill]]
title = "Image Processing"
value = "50%"

[[skill]]
title = "Web Development"
value = "30%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Spanish"
value = "Native"

[[language]]
title = "English"
value = "60%"

[[language]]
title = "Japanese"
value = "10%"